document.addEventListener("DOMContentLoaded",function(){let n;var c=[["M415.5,319.5Q446,389,381,443.5Q316,498,243,472.5Q170,447,104,383.5Q38,320,68,237Q98,154,184,114Q270,74,347,109Q424,144,409.5,222Q395,300,415.5,319.5Z","M343,116Q410,178,392.5,261Q375,344,332,430Q289,516,205,476Q121,436,144,357.5Q167,279,158.5,212Q150,145,218.5,119.5Q287,94,343,116Z","M380,320Q420,390,350,440Q280,490,210,450Q140,410,120,320Q100,230,170,180Q240,130,310,160Q380,190,380,320Z"],["M435,346.5Q379,443,271,460.5Q163,478,117.5,384Q72,290,150.5,217.5Q229,145,322.5,110Q416,75,453,186Q490,297,435,346.5Z","M377,99Q476,168,453.5,284.5Q431,401,324.5,429.5Q218,458,133,396.5Q48,335,103.5,237.5Q159,140,263,106.5Q367,73,377,99Z","M320,300Q360,360,300,420Q240,480,180,420Q120,360,140,300Q160,240,220,200Q280,160,320,220Q360,280,320,300Z"]];function e(e,r,s=8e3){let i=document.querySelector(`#${e} path`);if(i){let o=0,a=1;i.setAttribute("d",r[0]),!function e(){var t=(o+a+r.length)%r.length,n=s+2e3*Math.random();i.animate([{d:i.getAttribute("d")},{d:r[t]}],{duration:n,easing:"cubic-bezier(0.4, 0, 0.2, 1)",fill:"forwards"}),i.setAttribute("d",r[t]),0!=(o=t)&&o!==r.length-1||(a*=-1),setTimeout(e,n)}()}}e("blob1",c[0],7500),e("blob2",c[1],9200);var r=document.querySelector(".hero-bg .dots");if(r){var s=window.innerWidth<700?8:20;let t=[];for(let e=0;e<s;e++){var i=document.createElement("div"),l=(i.className="dot",["#667eea","#764ba2","#f093fb","#f5576c","#4facfe","#00f2fe"]),l=l[e%l.length],d=4+8*Math.random(),u=95*Math.random(),f=85*Math.random()+5;i.style.cssText=`
        top: ${f}vh;
        left: ${u}vw;
        width: ${d}px;
        height: ${d}px;
        background: radial-gradient(circle at 30% 30%, ${l}, transparent 70%);
        opacity: ${.3+.4*Math.random()};
        animation-delay: ${3*Math.random()}s;
        box-shadow: 0 0 ${2*d}px ${l}66;
      `,r.appendChild(i),t.push({element:i,baseX:u,baseY:f,offsetX:0,offsetY:0,speed:.5+1.5*Math.random()})}let o=0,a=0;document.addEventListener("mousemove",e=>{o=e.clientX/window.innerWidth*100,a=e.clientY/window.innerHeight*100}),!function e(){t.forEach(e=>{var t=o-e.baseX,n=a-e.baseY;Math.sqrt(t*t+n*n)<20&&(e.offsetX+=.1*t*e.speed,e.offsetY+=.1*n*e.speed),e.offsetX*=.95,e.offsetY*=.95,e.element.style.transform=`translate(${e.offsetX}px, ${e.offsetY}px) scale(${1+.2*Math.sin(.001*Date.now()+e.baseX)})`}),n=requestAnimationFrame(e)}()}let t=document.querySelector(".nav-toggle"),o=document.querySelector("nav ul"),a=document.querySelectorAll("nav ul a");t&&o&&(t.addEventListener("click",function(){var e=o.classList.contains("open");o.classList.toggle("open"),t.classList.toggle("open"),t.setAttribute("aria-expanded",!e),e||(a.forEach((e,t)=>{e.style.opacity="0",e.style.transform="translateX(-20px)",setTimeout(()=>{e.style.transition="opacity 0.3s ease, transform 0.3s ease",e.style.opacity="1",e.style.transform="translateX(0)"},50*t)}),a[0]&&a[0].focus())}),a.forEach(e=>{e.addEventListener("click",()=>{window.innerWidth<900&&(a.forEach((e,t)=>{setTimeout(()=>{e.style.opacity="0",e.style.transform="translateX(-20px)"},30*t)}),setTimeout(()=>{o.classList.remove("open"),t.classList.remove("open"),t.setAttribute("aria-expanded","false")},30*a.length+100))})})),document.querySelectorAll('nav a[href^="#"], .to-top').forEach(e=>{e.addEventListener("click",function(e){var t=this.getAttribute("href"),t=document.querySelector(t);if(t){e.preventDefault();e=t.offsetTop-80;let o=window.pageYOffset,a=e-o,r=800,s=null;requestAnimationFrame(function e(t){var t=t-(s=s||t),n=Math.min(t/r,1),n=n<.5?4*n*n*n:(n-1)*(2*n-2)*(2*n-2)+1;window.scrollTo(0,o+a*n),t<r&&requestAnimationFrame(e)})}})});var m,c=document.querySelectorAll(".reveal, .section");let h=new IntersectionObserver(e=>{e.forEach(e=>{e.isIntersecting&&((e=e.target).classList.add("visible"),e.querySelectorAll(".project-card, .achievement-slot, .blog-post, li").forEach((e,t)=>{e.style.opacity="0",e.style.transform="translateY(20px)",setTimeout(()=>{e.style.transition="opacity 0.5s ease, transform 0.5s ease",e.style.opacity="1",e.style.transform="translateY(0)"},100*t)}),h.unobserve(e))})},{threshold:.1,rootMargin:"0px 0px -50px 0px"}),y=(c.forEach(e=>{h.observe(e)}),[...document.querySelectorAll("section")]),v=[...document.querySelectorAll("nav ul li a")];function p(){var e,t=window.scrollY+120;let n=y[0];for(e of y)t>=e.offsetTop&&(n=e);v.forEach(e=>e.classList.remove("active"));var o=v.find(e=>e.getAttribute("href").slice(1)===n.id);o&&o.classList.add("active")}let g,w=(window.addEventListener("scroll",()=>{g&&clearTimeout(g),g=setTimeout(p,10)}),document.getElementById("typewriter"));if(w){let n=w.textContent,o=0;w.innerHTML='<span class="cursor">|</span>';c=document.createElement("style");c.textContent=`
      .cursor {
        animation: blink 1s infinite;
        color: #667eea;
      }
      @keyframes blink {
        0%, 50% { opacity: 1; }
        51%, 100% { opacity: 0; }
      }
    `,document.head.appendChild(c),setTimeout(function e(){var t;o<n.length?(t=n.charAt(o),w.querySelector(".cursor").insertAdjacentText("beforebegin",t),o++,t=" "===t?100:50+100*Math.random(),setTimeout(e,t)):setTimeout(()=>{var e=w.querySelector(".cursor");e&&e.remove()},1e3)},500)}c=".tilt-hover",m=12,700<window.innerWidth&&document.querySelectorAll(c).forEach(e=>{let o=!1;e.addEventListener("mouseenter",function(){o=!0,this.style.transition="transform 0.1s ease-out"}),e.addEventListener("mousemove",function(e){var t,n;o&&(n=(t=this.getBoundingClientRect()).left+t.width/2,n=(e.clientX-n)/(t.width/2),this.style.transform=`
            perspective(1000px) 
            rotateX(${-((e.clientY-(t.top+t.height/2))/(t.height/2))*m}deg) 
            rotateY(${n*m}deg) 
            scale(1.05)
            translateZ(20px)
          `,this.style.boxShadow=`
            0 20px 40px rgba(102, 126, 234, 0.3),
            0 0 0 1px rgba(255, 255, 255, 0.1)
          `)}),e.addEventListener("mouseleave",function(){o=!1,this.style.transition="transform 0.3s ease, box-shadow 0.3s ease",this.style.transform="",this.style.boxShadow=""})});let E=document.querySelector(".to-top");if(E){let n=document.createElement("div");function b(){var e=window.pageYOffset,t=113-113*(e/(document.documentElement.scrollHeight-window.innerHeight));n.querySelector("circle:last-child").style.strokeDashoffset=t,300<e?(E.style.opacity="1",E.style.pointerEvents="auto",E.style.transform="translateY(0) scale(1)"):(E.style.opacity="0",E.style.pointerEvents="none",E.style.transform="translateY(20px) scale(0.8)")}n.innerHTML=`
      <svg width="40" height="40" style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%);">
        <circle cx="20" cy="20" r="18" fill="none" stroke="rgba(255,255,255,0.2)" stroke-width="2"/>
        <circle cx="20" cy="20" r="18" fill="none" stroke="#667eea" stroke-width="2" 
                stroke-dasharray="113" stroke-dashoffset="113" 
                style="transform: rotate(-90deg); transform-origin: center; transition: stroke-dashoffset 0.1s ease;"/>
      </svg>
    `,E.appendChild(n),window.addEventListener("scroll",b),b()}c=document.querySelector(".carousel-certificates");if(c){let e=c.querySelectorAll("img");var Q=document.querySelector(".carousel-cert-btn.prev"),L=document.querySelector(".carousel-cert-btn.next");let n=document.querySelector(".carousel-cert-indicators"),o=0,a=e.length,t,r=!0;n.innerHTML="";for(let t=0;t<a;t++){var x=document.createElement("span");x.className="dot",0===t&&x.classList.add("active"),x.tabIndex=0,x.setAttribute("aria-label","Show certificate "+(t+1)),x.addEventListener("click",()=>S(t)),x.addEventListener("keydown",e=>{"Enter"===e.key&&S(t)}),n.appendChild(x)}Q.addEventListener("click",M),L.addEventListener("click",A),c.addEventListener("mouseenter",T),c.addEventListener("mouseleave",k),c.addEventListener("keydown",e=>{"ArrowLeft"===e.key&&M(),"ArrowRight"===e.key&&A()," "===e.key&&(e.preventDefault(),((r=!r)?k:T)())});let s=null,i=null,l=!1;function q(){e.forEach((e,t)=>{var n=100*(t-o);e.style.transform=`translateX(${n}%) scale(${t===o?1:.9})`,e.style.opacity=t===o?"1":"0.7",e.style.zIndex=t===o?"2":"1"}),n.querySelectorAll(".dot").forEach((e,t)=>{e.classList.toggle("active",t===o)})}function S(e){o=(e+a)%a,q(),Y()}function A(){S(o+1)}function M(){S(o-1)}function k(){r&&(t=setInterval(A,4e3))}function T(){clearInterval(t)}function Y(){T(),k()}c.addEventListener("touchstart",function(e){s=e.touches[0].clientX,i=e.touches[0].clientY,l=!0,T()},{passive:!0}),c.addEventListener("touchmove",function(e){var t,n;l&&null!==s&&(t=e.touches[0].clientX,n=e.touches[0].clientY,t=s-t,n=i-n,Math.abs(t)>Math.abs(n))&&50<Math.abs(t)&&(e.preventDefault(),(0<t?A:M)(),l=!1,s=null)},{passive:!1}),c.addEventListener("touchend",function(){l=!1,s=null,i=null,Y()}),q(),k()}document.querySelectorAll('img[loading="lazy"]').forEach(e=>{e.addEventListener("load",function(){this.style.opacity="0",this.style.transform="scale(0.9)",this.style.transition="opacity 0.5s ease, transform 0.5s ease",setTimeout(()=>{this.style.opacity="1",this.style.transform="scale(1)"},100)})}),"performance"in window&&window.addEventListener("load",()=>{setTimeout(()=>{var e=performance.getEntriesByType("navigation")[0];console.log(`Page load time: ${e.loadEventEnd-e.loadEventStart}ms`)},0)}),window.addEventListener("beforeunload",()=>{n&&cancelAnimationFrame(n),clearInterval(autoPlayInterval)})});